# Generated by Django 6.0.3 on 2026-03-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='scholorship',
            field=models.CharField(choices=[('100', '100%'), ('75', '75%'), ('50', '50%'), ('25', '25%'), ('10', '10%'), ('0', 'No Scholarship')], default='0', max_length=3),
        ),
    ]
